apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-omoh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-omoh@sha256:81a2f48b2eb64b874880c5ad488b451618c0df00e0ec4fcf4735db7a2efb58b0
        name: my-python
        resources: {}
status: {}
