apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-1juk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-1juk@sha256:4960cc728797e417e86d248677263d974d008fde617c5618fd02f5e807e0e468
        name: my-nodejs
        resources: {}
status: {}
